# See: https://github.com/cloudhut/kowl/tree/master/docs/config for reference config files.
kafka:
  brokers:
    - kafka1:9092
  schemaRegistry:
    enabled: true
    urls: ["http://schemaregistry:8085"]
# server:
  # listenPort: 8080