
name: Docker Image on new release

on:
  release:
    types: [published]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Extract ref/branch name
        shell: bash
        run: echo "##[set-output name=ref;]$(echo ${GITHUB_REF##*/})"
        id: extract_ref

      - name: Set timestamp
        shell: bash
        run: echo "::set-output name=time::$(date +%s)"
        id: set_timestamp

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        run:
          docker build
          --build-arg "KOWL_GIT_SHA=${GITHUB_SHA}"
          --build-arg "KOWL_GIT_REF=${{ steps.extract_ref.outputs.ref }}"
          --build-arg "KOWL_TIMESTAMP=${{ steps.set_timestamp.outputs.time }}"
          -t ghcr.io/lcfyi/kowl:${{ steps.extract_ref.outputs.ref }}
          .

      - name: Push Image
        run: |
          docker push ghcr.io/lcfyi/kowl:${{ steps.extract_ref.outputs.ref }}
